package com.ironmeddieapps.remote.dto

import com.ironmeddieapps.models.CurencyItem

data class ValuteDto(
    val AED: AED,
    val AMD: AMD,
    val AUD: AUD,
    val AZN: AZN,
    val BGN: BGN,
    val BRL: BRL,
    val BYN: BYN,
    val CAD: CAD,
    val CHF: CHF,
    val CNY: CNY,
    val CZK: CZK,
    val DKK: DKK,
    val EGP: EGP,
    val EUR: EUR,
    val GBP: GBP,
    val GEL: GEL,
    val HKD: HKD,
    val HUF: HUF,
    val IDR: IDR,
    val INR: INR,
    val JPY: JPY,
    val KGS: KGS,
    val KRW: KRW,
    val KZT: KZT,
    val MDL: MDL,
    val NOK: NOK,
    val NZD: NZD,
    val PLN: PLN,
    val QAR: QAR,
    val RON: RON,
    val RSD: RSD,
    val SEK: SEK,
    val SGD: SGD,
    val THB: THB,
    val TJS: TJS,
    val TMT: TMT,
    val TRY: TRY,
    val UAH: UAH,
    val USD: USD,
    val UZS: UZS,
    val VND: VND,
    val XDR: XDR,
    val ZAR: ZAR
){
    fun toList(): List<CurencyItem>{
        return listOf(
            AED.toItem(),
        AMD.toItem(),
        AUD.toItem(),
        AZN.toItem(),
        BGN.toItem(),
        BRL.toItem(),
        BYN.toItem(),
        CAD.toItem(),
        CHF.toItem(),
        CNY.toItem(),
        CZK.toItem(),
        DKK.toItem(),
        EGP.toItem(),
        EUR.toItem(),
        GBP.toItem(),
        GEL.toItem(),
        HKD.toItem(),
        HUF.toItem(),
        IDR.toItem(),
        INR.toItem(),
        JPY.toItem(),
        KGS.toItem(),
        KRW.toItem(),
        KZT.toItem(),
        MDL.toItem(),
        NOK.toItem(),
        NZD.toItem(),
        PLN.toItem(),
        QAR.toItem(),
        RON.toItem(),
        RSD.toItem(),
        SEK.toItem(),
        SGD.toItem(),
        THB.toItem(),
        TJS.toItem(),
        TMT.toItem(),
        TRY.toItem(),
        UAH.toItem(),
        USD.toItem(),
        UZS.toItem(),
        VND.toItem(),
        XDR.toItem(),
        ZAR.toItem()
        )
    }
}